apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-pm
spec:
  podMetadata:
    labels:
      prometheus: prometheus        
  serviceAccountName: prometheus-yann
  podMonitorSelector:
    matchLabels:
      team: frontend
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false

