apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sample-monitor
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: example-app-l
  endpoints:
  - port: web
