apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: sample-monitor-p
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: example-app-l
  podMetricsEndpoints:
  - port: web
